# Generated by Django 2.2.12 on 2020-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=30)),
                ('option_two', models.CharField(max_length=30)),
                ('option_three', models.CharField(max_length=30)),
                ('option_one_count', models.ImageField(default=0, upload_to='')),
                ('option_two_count', models.ImageField(default=0, upload_to='')),
                ('option_three_count', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
